language: php

php:
    - 5.6
    - 7.0
    - hhvm

env:
  - SYMFONY_VERSION=2.3.*

before_isntall:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source

install: composer update --prefer-dist --no-progress

script: vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.4.*
    - php: 5.6
      env: SYMFONY_VERSION=2.5.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7.0
      env: SYMFONY_VERSION=3.0.*




